# Site settings
title: Salt
email: info@uncharted.software
description: > # this means to ignore newlines until "baseurl:"
  Looking at big data? Add a little salt.
baseurl: "/salt/" # the subpath of your site, e.g. /blog/
url: "//unchartedsoftware.github.io" # the base hostname & protocol for your site
latest: "2.0.1"

googleAnalytics: UA-21723198-11

# Build settings
markdown: kramdown
highlighter: pygments
